---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - mynginx.opencanon.io
  resources:
  - monitorings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mynginx.opencanon.io
  resources:
  - monitorings/finalizers
  verbs:
  - update
- apiGroups:
  - mynginx.opencanon.io
  resources:
  - monitorings/status
  verbs:
  - get
  - patch
  - update
