# This rule is not used by the project operator-mar269-2025 itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the mynginx.opencanon.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator-mar269-2025
    app.kubernetes.io/managed-by: kustomize
  name: monitoring-editor-role
rules:
- apiGroups:
  - mynginx.opencanon.io
  resources:
  - monitorings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mynginx.opencanon.io
  resources:
  - monitorings/status
  verbs:
  - get
